name: Deploy to VM # Tên của workflow, sẽ hiển thị trên tab Actions của GitHub

on:
  push: # Sự kiện kích hoạt workflow
    branches:
      - main # Chỉ chạy khi có push lên nhánh 'main'. Bạn có thể đổi thành nhánh khác.

jobs:
  deploy:
    name: Deploy Code to VM
    runs-on: self-hosted 

    steps:
      - name: Print Starting Message
        run: echo "🚀 Starting deployment process on VM via GitHub Actions..."

      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Pull latest code into project directory
        run: |
          echo "Navigating to project directory and pulling latest code..."
          cd /home/vagrant/test_action_github
          git pull origin main
          echo "✅ Code pulled successfully!"

      - name: Install/Update Node.js dependencies
        run: |
          echo "Installing/updating dependencies..."
          cd /home/vagrant/test_action_github
          npm install --production 
          echo "✅ Dependencies installed/updated!"

      - name: Restart Node.js Application
        run: |
          echo "Gracefully restarting Node.js application with PM2..."
          pm2 restart my-api
          echo "✅ Application restarted via PM2!"